/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#490006",
        "error-container": "#9f0519",
        "on-surface-variant": "#adaaaa",
        "outline": "#777575",
        "surface-bright": "#2c2c2c",
        "primary-fixed": "#4ade80",
        "on-background": "#ffffff",
        "inverse-surface": "#fcf8f8",
        "surface-container-highest": "#262626",
        "surface": "#0e0e0e",
        "secondary-container": "#006877",
        "on-secondary-fixed-variant": "#005966",
        "tertiary-fixed-dim": "#8c9cff",
        "secondary-dim": "#3adffa",
        "on-error-container": "#ffa8a3",
        "on-secondary-fixed": "#003a43",
        "primary": "#4ade80",
        "secondary-fixed-dim": "#29d6f1",
        "on-surface": "#ffffff",
        "tertiary-fixed": "#9eabff",
        "inverse-primary": "#006e36",
        "surface-container-high": "#201f1f",
        "on-tertiary-fixed-variant": "#0d299e",
        "on-tertiary": "#00156e",
        "on-secondary-container": "#eafbff",
        "background": "#0e0e0e",
        "primary-container": "#19be64",
        "primary-fixed-dim": "#4ade80",
        "primary-dim": "#4ade80",
        "on-primary": "#005f2e",
        "inverse-on-surface": "#565554",
        "secondary-fixed": "#48e4ff",
        "on-tertiary-container": "#000a47",
        "tertiary-dim": "#8596ff",
        "on-secondary": "#004b56",
        "error-dim": "#d7383b",
        "tertiary-container": "#768afe",
        "surface-variant": "#262626",
        "surface-container": "#1a1919",
        "tertiary": "#8899ff",
        "error": "#ff716c",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "surface-tint": "#4ade80",
        "secondary": "#3adffa",
        "outline-variant": "#494847",
        "on-primary-container": "#002f13",
        "on-tertiary-fixed": "#000d52",
        "on-primary-fixed-variant": "#006a34",
        "on-primary-fixed": "#004a22",
        "surface-container-low": "#131313"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Space Grotesk"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
